<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="anhhn-HP-EliteBook-8470p" failures="9" tests="22" name="TestSuite.OrderProductWithLogin" time="350.243" errors="0" timestamp="2023-08-20T00:31:31 ICT" skipped="0">
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_39" time="13.636"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_56" time="14.954"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_41" time="16.176"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_52" time="15.246"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_53" time="16.668"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_43" time="16.182">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_43(OrderProductWithLogin.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_43 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_38" time="14.963"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_44" time="16.996">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_44(OrderProductWithLogin.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_44 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_49" time="16.397">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_49(OrderProductWithLogin.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_49 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_50" time="14.657">
    <failure message="Value is not correct: Expected: &quot;Địa chỉ giao hàng không được để trống&quot;; Actual: &quot;Địa chỉ nhận hàng không được để trống&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Địa chỉ giao hàng không được để trống"; Actual: "Địa chỉ nhận hàng không được để trống"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_50(OrderProductWithLogin.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_50 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_57" time="15.252"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_58" time="16.009"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_55" time="14.608"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_54" time="17.359"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_42" time="17.346">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Số điện thoại không quá 11 số&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Số điện thoại không quá 11 số"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_42(OrderProductWithLogin.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_42 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_45" time="16.731">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_45(OrderProductWithLogin.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_45 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_51" time="20.827">
    <failure message="Value is not correct: Expected: &quot;Địa chỉ giao hàng không được để trống&quot;; Actual: &quot;Địa chỉ nhận hàng không được để trống&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Địa chỉ giao hàng không được để trống"; Actual: "Địa chỉ nhận hàng không được để trống"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_51(OrderProductWithLogin.java:95)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_51 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_40" time="14.661"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_47" time="15.933"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_46" time="16.144">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_46(OrderProductWithLogin.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_46 -->
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_59" time="15.809"/>
  <testcase classname="TestSuite.OrderProductWithLogin" name="TC_09_48" time="13.689">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithLogin(PaymentInfoScreen.java:56)
at TestSuite.OrderProductWithLogin.TC_09_48(OrderProductWithLogin.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_48 -->
</testsuite> <!-- TestSuite.OrderProductWithLogin -->
