<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="anhhn-HP-EliteBook-8470p" failures="14" tests="37" name="TestSuite.OrderProductWithoutLogin" time="537.854" errors="0" timestamp="2023-08-20T01:03:42 ICT" skipped="0">
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_34" time="13.963"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_27" time="14.675"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_10" time="14.385">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Số điện thoại không quá 11 số&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Số điện thoại không quá 11 số"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_10(OrderProductWithoutLogin.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_10 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_04" time="14.249"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_37" time="14.450"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_07" time="13.862"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_02" time="14.978"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_30" time="14.278"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_31" time="14.440"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_32" time="14.499"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_03" time="15.393"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_36" time="14.309"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_11" time="14.230">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_11(OrderProductWithoutLogin.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_11 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_09" time="13.954"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_35" time="14.615"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_25" time="14.231">
    <failure message="Value is not correct: Expected: &quot;Email không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Email không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_25(OrderProductWithoutLogin.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_25 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_18" time="14.067"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_33" time="14.085"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_01" time="15.175"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_24" time="14.884">
    <failure message="Value is not correct: Expected: &quot;Email không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Email không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_24(OrderProductWithoutLogin.java:145)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_24 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_08" time="14.531"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_06" time="14.778"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_05" time="14.881"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_21" time="14.344">
    <failure message="Value is not correct: Expected: &quot;Email không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Email không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_21(OrderProductWithoutLogin.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_21 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_12" time="14.316">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_12(OrderProductWithoutLogin.java:85)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_12 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_23" time="14.544">
    <failure message="Value is not correct: Expected: &quot;Email không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Email không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_23(OrderProductWithoutLogin.java:140)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_23 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_13" time="14.078">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_13(OrderProductWithoutLogin.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_13 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_29" time="15.092">
    <failure message="Value is not correct: Expected: &quot;Địa chỉ giao hàng không được để trống&quot;; Actual: &quot;Địa chỉ nhận hàng không được để trống&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Địa chỉ giao hàng không được để trống"; Actual: "Địa chỉ nhận hàng không được để trống"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_29(OrderProductWithoutLogin.java:170)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_29 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_26" time="14.480"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_19" time="14.331"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_22" time="17.143">
    <failure message="Value is not correct: Expected: &quot;Email không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Email không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_22(OrderProductWithoutLogin.java:135)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_22 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_28" time="14.315">
    <failure message="Value is not correct: Expected: &quot;Địa chỉ giao hàng không được để trống&quot;; Actual: &quot;Địa chỉ nhận hàng không được để trống&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Địa chỉ giao hàng không được để trống"; Actual: "Địa chỉ nhận hàng không được để trống"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_28(OrderProductWithoutLogin.java:165)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_28 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_14" time="14.811">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_14(OrderProductWithoutLogin.java:95)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_14 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_16" time="14.352">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_16(OrderProductWithoutLogin.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_16 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_17" time="14.460">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:353)
at Common.Utilities.assertTextValue(Utilities.java:303)
at Common.Utilities.assertTextValueVisible(Utilities.java:310)
at CommonScreen.PaymentInfoScreen.orderProductWithoutLogin(PaymentInfoScreen.java:47)
at TestSuite.OrderProductWithoutLogin.TC_09_17(OrderProductWithoutLogin.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_09_17 -->
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_15" time="14.573"/>
  <testcase classname="TestSuite.OrderProductWithoutLogin" name="TC_09_20" time="14.103"/>
</testsuite> <!-- TestSuite.OrderProductWithoutLogin -->
