<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="anhhn-HP-EliteBook-8470p" failures="8" tests="25" name="TestSuite.OrderWithoutLogin" time="265.036" errors="0" timestamp="2023-04-25T23:04:34 ICT" skipped="0">
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_13" time="11.603"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_27" time="10.190"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_19" time="10.400">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Số điện thoại không quá 11 số&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Số điện thoại không quá 11 số"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_19(OrderWithoutLogin.java:86)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_19 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_16" time="10.653">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_16(OrderWithoutLogin.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_16 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_31" time="10.168"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_25" time="10.365">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Số điện thoại không quá 11 số&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Số điện thoại không quá 11 số"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_25(OrderWithoutLogin.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_25 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_22" time="10.608">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_22(OrderWithoutLogin.java:101)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_22 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_14" time="10.811"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_33" time="10.747"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_12" time="10.401"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_23" time="11.146"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_15" time="10.296"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_09" time="10.917"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_18" time="10.054">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_18(OrderWithoutLogin.java:81)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_18 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_29" time="10.228"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_20" time="10.628">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Số điện thoại không quá 11 số&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Số điện thoại không quá 11 số"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_20(OrderWithoutLogin.java:91)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_20 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_10" time="10.593"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_21" time="10.479">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_21(OrderWithoutLogin.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_21 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_17" time="10.700">
    <failure message="Value is not correct: Expected: &quot;Số điện thoại không hợp lệ&quot;; Actual: &quot;Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận.&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Số điện thoại không hợp lệ"; Actual: "Cám ơn bạn. Đơn hàng của bạn đã được tiếp nhận."
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:485)
at Common.Utilities.assertTextValue(Utilities.java:417)
at Common.Utilities.assertTextValueVisible(Utilities.java:431)
at CommonScreen.PaymentInfoScreen.orderWithoutLogin(PaymentInfoScreen.java:44)
at TestSuite.OrderWithoutLogin.ITS_08_17(OrderWithoutLogin.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ITS_08_17 -->
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_28" time="10.633"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_30" time="10.790"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_32" time="10.686"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_24" time="10.485"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_26" time="10.716"/>
  <testcase classname="TestSuite.OrderWithoutLogin" name="ITS_08_11" time="10.739"/>
</testsuite> <!-- TestSuite.OrderWithoutLogin -->
